spring.application.name=webboard

# 로그 색상
spring.output.ansi.enabled=always

# 로그 설정
logging.level.root=info

## H2 DB Setting
spring.h2.console.enabled=true
# 콘솔 URL
spring.h2.console.path=/h2-console
# H2 DB 파일 위치
spring.datasource.url=jdbc:h2:./local
# H2 DB 접속용 드라이버
spring.datasource.driver-class-name=org.h2.Driver
# H2 DB 접속계정
spring.datasource.username=sa
spring.datasource.password=12345

## JPA DB Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# create : 서버 실행될 때마다 드랍(다지우고)하고 새로 테이블 생(만듦), update : 최초 없으면 생성, 이전 DB를 그대로 보관 // create 쓰면 다날라가니깐 update로 유지하기
spring.jpa.hibernate.ddl-auto=update
# 로그 쿼리 출력
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true