spring.application.name=publicapi

spring.output.ansi.enabled=always

logging.level.root=info

# OpenAPI 관련 서버 정보
# 개발자(우리)가 추가 생성한 설정 정보
redtable.service-key=bUZC7dAtcOb0CqF9EpKUDsx94UMuTqRmM6K00FtLhHuaoa1QrNc7oL48b2Lcx3xe
redtable.base-url=https://busan-food.openapi.redtable.global