-- 회원테이블
CREATE TABLE USER_ACCOUNT (
    USER_ID      NUMBER         PRIMARY KEY,
    LOGIN_ID     VARCHAR2(50)   NOT NULL UNIQUE,
    PASSWORD     VARCHAR2(255)  NOT NULL,
    NAME         VARCHAR2(100)  NOT NULL,
    ROLE         VARCHAR2(30)   DEFAULT 'ROLE_USER' NOT NULL,
    CREATED_AT   DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE
);

-- 회원용 시퀀스
CREATE SEQUENCE USER_ACCOUNT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;