CREATE TABLE USER_SOCIAL_ACCOUNT (
    SOCIAL_ID         NUMBER PRIMARY KEY,
    USER_ID           NUMBER NOT NULL,
    PROVIDER          VARCHAR2(30) NOT NULL,
    PROVIDER_USER_ID  VARCHAR2(100) NOT NULL,
    EMAIL             VARCHAR2(200),
    NAME              VARCHAR2(100),
    PROFILE_IMAGE     VARCHAR2(500),
    CREATED_AT        DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT        DATE,
    CONSTRAINT FK_USER_SOCIAL_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_USER_SOCIAL_PROVIDER
        UNIQUE (PROVIDER, PROVIDER_USER_ID)
);

CREATE SEQUENCE USER_SOCIAL_ACCOUNT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 기존 USERTable Password 필드를 수정
ALTER TABLE USER_ACCOUNT MODIFY PASSWORD VARCHAR2(255) NULL;

-- USER_ACCOUNT LOGIN_ID 길이변경(이메일 입력)
ALTER TABLE USER_ACCOUNT MODIFY LOGIN_ID VARCHAR2(200);