/*
 * This source file was generated by the Gradle 'init' task
 */
package ex01;

public class App {
    public static void main(String[] args) {
        int a;
        float b;
        double c;
        String d;
        boolean e;
        long f;
        char g;
        
        System.out.println(new App().getGreeting());
    }
}
