-- 게시판
CREATE TABLE BOARD (
    BOARD_ID        NUMBER          PRIMARY KEY,
    TITLE           VARCHAR2(200)   NOT NULL,
    CONTENT         CLOB            NOT NULL,
    WRITER          VARCHAR2(100)   NOT NULL,
    CREATED_AT      DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE
);

-- 게시판 시퀀스
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;