spring.application.name=webboard

# 로그 색상
spring.output.ansi.enabled=always



# 로그 설정
logging.level.root=info

## H2 DB Settings
# spring.h2.console.enabled=true
# 콘솔 URL
# spring.h2.console.path=/h2-console
# H2 DB 파일 위치
# spring.datasource.url=jdbc:h2:./local
# H2 DB 접속용 드라이버
# spring.datasource.driver-class-name=org.h2.Driver
# H2 DB 접속계정
# spring.datasource.username=sa
# spring.datasource.password=12345

## Oracle DB Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=bookrentalshop
spring.datasource.password=java12345

## JPA DB Settings
# H2 JPA
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# Oracle JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
# create : 서버 실행될때마다 새로 테이블 생성, update : 최초없으면 생성, 이전 DB를 그대로 보관
spring.jpa.hibernate.ddl-auto=update
# 로그 쿼리 출력
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

