CREATE TABLE REPLY (
    REPLY_ID         NUMBER          PRIMARY KEY,
    BOARD_ID         NUMBER          NOT NULL,
    REPLY_CONTENT    VARCHAR2(1000)  NOT NULL,
    REPLY_WRITER     VARCHAR2(100)   NOT NULL,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_REPLY_BOARD
        FOREIGN KEY (BOARD_ID)
        REFERENCES BOARD (BOARD_ID)
);

CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;