spring.application.name=studygroup

## 세션 만료 시간
# 1시간 유지
# server.servlet.session.timeout=1h 

## 서버 이미지(파일) 저장경로
# 실제 서버 저장 경로. 되도록 \ 쓰지 말것
file.upload-dir=D:/upload/studygroup
file.access-url=/upload/site
# 서버에서 파일업로드 제약사항 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

## 로그관련 설정
# 로그 색상
spring.output.ansi.enabled=always
# 로그레벨 설정
logging.level.root=info
# Mybatis로그
logging.level.com.pknu26.studygroup.mapper=debug
logging.level.org.mybatis=debug
logging.level.java.sql=debug

## Oracle DB 설정
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=studygroup
spring.datasource.password=java12345

## MyBatis 설정
# MyBatis 쿼리저장 위치
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.pknu26.studygroup.dto
mybatis.configuration.map-underscore-to-camel-case=true

## Thymeleaf 설정 - 개발때만 추가
spring.thymeleaf.cache=false
