/*
 * This source file was generated by the Gradle 'init' task
 */
package ex05_fileio;

import java.io.*;   // java.io 밑에 있는 모든 클래스를 쓸거야

public class App {
    public static void main(String[] args) {
        System.out.println("파일 쓰고 읽기");

        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("output.txt"));

            bw.write("자바 파일쓰기입니다.");
            bw.newLine();
            bw.write("자바 파일 쓰기 테스트~!");

            bw.close();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        System.out.println("파일쓰기 완료");
        System.out.println("파일읽기 시작!");

        // 좀 더 효율적인 방법
        try (BufferedReader br = new BufferedReader(new FileReader("output.txt"))) {

            String line;
            while ((line = br.readLine()) != null) {
                System.out.println(line);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        // 파일정보 확인
        System.out.println("파일 정보확인");

        File file = new File("output.txt");

        System.out.println("파일 존재 여부 : " + file.exists());
        System.out.println("파일 크기 : " + file.length());
        System.out.println("파일 경로 : " + file.getAbsolutePath());

        // 람다함수
        iCalculator add = (int a, int b) -> a + b;  // 아주 간단한 로직을 처리하는 함수
        int result = add.calc(5, 6);
        System.out.println("결과는 " + result);
    }
}

interface iCalculator {
    int calc(int a, int b);
}