spring.application.name=studygroup

## 로그관련 설정
# 로그 색상
spring.output.ansi.enabled=always
# 로그레벨 설정
logging.level.root=info
# Mybatis 로그
logging.level.com.pknu26.stuydygroup.mapper=DEBUG
logging.level.org.mybatis=DEBUG

## Oracle DB 설정
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=studygroup
spring.datasource.password=java12345

## MyBatis 설정
# MyBatis 쿼리 저장 위치
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.pknu26.studygroup.dto
mybatis.configuration.map0underscore-to-camel-case=true