CREATE TABLE SITE_CONTENT (
    ID             NUMBER PRIMARY KEY,
    CONTENT_KEY    VARCHAR2(100) NOT NULL UNIQUE,
    CONTENT_BODY   VARCHAR2(4000) NOT NULL,
    CREATED_AT     DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_SITE_CONTENT INCREMENT BY 1 MINVALUE 1 
NOCYCLE NOCACHE;

INSERT INTO SITE_CONTENT (ID, CONTENT_KEY, CONTENT_BODY)
VALUES (SEQ_SITE_CONTENT.NEXTVAL, 'CAROUSEL_1_TITLE', 'StudyMate 2026');

INSERT INTO SITE_CONTENT (ID, CONTENT_KEY, CONTENT_BODY)
VALUES (SEQ_SITE_CONTENT.NEXTVAL, 'CAROUSEL_1_CONTENT', '오프라인으로 스터디할 사람들을 모집하는 사이트입니다!');

COMMIT;

-- 사용여부 컬럼 추가
ALTER TABLE SITE_CONTENT ADD USE_YN CHAR(1) DEFAULT 'Y' NOT NULL;