CREATE TABLE SITE_IMAGE (
    ID           NUMBER PRIMARY KEY,
    IMAGE_KEY    VARCHAR2(100) NOT NULL UNIQUE,
    IMAGE_PATH   VARCHAR2(500) NOT NULL,
    USE_YN       CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_SITE_IMAGE
START WITH 1
INCREMENT BY 1
NOCACHE;