spring.application.name=studygroup

## 로그관련 설정
# 로그 색상
spring.output.ansi.enabled=always
# 로그레벨 설정
logging.level.root=info
# Mybatis로그
logging.level.com.pknu26.studygroup.mapper=debug
logging.level.org.mybatis=debug
logging.level.java.sql=debug

## Oracle DB 설정
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=studygroup
spring.datasource.password=java12345

## MyBatis 설정
# MyBatis 쿼리저장 위치
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.pknu26.studygroup.dto
mybatis.configuration.map-underscore-to-camel-case=true

## Thymeleaf 설정 - 개발때만 추가
spring.thymeleaf.cache=false
