/*
 * This source file was generated by the Gradle 'init' task
 */
package ex06_generic;

public class App {
    public static void main(String[] args) {
        System.out.println("Generic 학습");
    
        // Box box = new Box();
        // box.set("문자열");  // Object <- 문자열 할당
        // box.set(1000);
        // // box.set(true);

        // String s = (String) box.get(); // 형변환 필요
        // System.out.println(s);
        // Box<String> box = new Box<>();
        // box.set("10000");
        
        Box<Integer> box_n = new Box<>();
        box_n.set(10000);

        System.out.println(box_n.get());

        Box<Number> box3 = new Box<>();
        box3.set(1000);
        box3.set(3.14f);
        box3.set(300000L);

        Pair<String, Integer> p1 = new Pair<>();
        Pair<Integer, Float> p2 = new Pair<>();

        p1.key = "Power";
        p1.value = 10000;

        p2.key = 9090;
        p2.value = 4.267f;
    }
}

    // 두 타입을 받는데 어떤타입이든 받을 수 있다.
    class Pair<K, V> {
        K key;
        V value;
    }

    class Box<T> {  // T -> 아무 타입이나 상관없음
    T value;  // 멤버 필드. 무슨타입이든지 받을 수 있음.

    // setter
    void set(T value) {
        this.value = value;
    }
    // getter
    T get() {
        return this.value;
    }
}